### ISSUE TITLE
Missing documentation/error

### ISSUE THREAD

**Issue by TimothyMakkison** [paseto-standard/paserk#13]
I've been trying to implement PBKD in [paseto-dotnet](https://github.com/daviddesmet/paseto-dotnet) and I think I've found an error in the tests/test vectors. I couldn't tell why my tests kept failing until I looked at the [implementation](https://github.com/paragonie/paserk-php/blob/master/tests/KAT/LocalPWTest.php). 
```
 $wrapper = new LocalPW(
                new HiddenString(Hex::encode($test['password'])),
                $test['options'] ?? [],
                $version
            );
```
I don't know php, but it looks like the password is converted into a hex string and then back into bytes to be used by `hash_pbkdf2`. 
```
PasswordString -> Utf8Bytes -> HexString -> Utf8Bytes
"Hello World" -> ("Hello World" bytes) -> "48656C6C6F20576F726C64" -> ("48656C6C6F20576F726C64" bytes)
```
When I recreated this converter in C# my tests passed.
``` C#
// Convert HexString to lower because php HexString uses lowercase.
var passwordBytes = Encoding.UTF8.GetBytes(Convert.ToHexString(Encoding.UTF8.GetBytes(password)).ToLower());
```

Is this intentional? I reread the spec and couldn't find any mention of encoding the password this way.

**Comment by paragonie-security** [comment]
Correct. It looks like there's a pasto in the test vector generation.

**Comment by paragonie-security** [comment]
The test vectors have been updated.
