### ISSUE TITLE
Suggestions/query

### ISSUE THREAD

**Issue by TimothyMakkison** [paseto-standard/paserk#14]
Hey, I've been implementing PBKW and had some thoughts/queries. I hope they might help others.

1. The test vectors for PBKW V2 & V4 don't give the value for parallelism in the options section. I assumed degreeOfParallelism is 1 by default.
2.  PBKW never specified that `long2bytes` and `int2bytes` convert to the big endian, form. `local-pw` and `secret-pw` only state that `mem`, `time`, `para` & `i` are big endian encoded when added to the paserk data.
3.  In PBKW the length of `ek` is not mentioned (usually 32 bytes).
4. The length of `k` is not stated (32 bytes) for `k = Argon2id(pw, s, mem, time, para)`.
5. PBKW or pie does not say that `crypto_generichash` is `blake2b264`, the only time this is stated is in [ID](https://github.com/paseto-standard/paserk/blob/master/operations/ID.md).

Should the public api for `Encode` `local-pw` and `secret-pw` take `memoryCost` in bytes or KiBytes? The test vectors use bytes but Argon2id work in blocks of 1 KiBytes. Should this be left to the implementer to decide?

**Comment by paragonie-security** [comment]
> The test vectors for PBKW V2 & V4 don't give the value for parallelism in the options section. I assumed degreeOfParallelism is 1 by default.

Correct, because the PHP bindings for libsodium don't allow this to be configured, and therefore I cannot implement support for them in the reference implementation (PHP).

> BKW never specified that long2bytes and int2bytes convert to the big endian, form. local-pw and secret-pw only state that mem, time, para & i are big endian encoded when added to the paserk data.

Thanks, I'll make that clearer.

> In PBKW the length of ek is not mentioned (usually 32 bytes).

Thanks, I'll be more explicit.

> The length of k is not stated (32 bytes) for k = Argon2id(pw, s, mem, time, para).

Thanks, I'll be more explicit.

> PBKW or pie does not say that crypto_generichash is blake2b264, the only time this is stated is in [ID](https://github.com/paseto-standard/paserk/blob/master/operations/ID.md).

That's implied by libsodium's API, which is what PASERK implementations SHOULD be using.

**Comment by paragonie-security** [comment]
See #15 for the proposed edits.
